import "./globals.css";
import { Manrope } from "next/font/google";
import Header from "../components/Header";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope.className} h-full antialiased`}
    >
      <body className="min-h-full max-w-93.75 mx-auto my-5 p-4.5 border-black border-solid border rounded-2xl">
        <Header />
        {children}
      </body>
    </html>
  );
}
